### ISSUE TITLE
Can't find lib.php

### ISSUE THREAD

**Issue by jmcscript** [jasonpetersen/anonynote#1]
Hello, Jason (I presume)!

I'm trying to set up your project, but **index.php** errors out when references are made to **lib.php**. Apparently, that file should be under `./min/static/lib.php`. However, I can't find it anywhere. Would you be able to assist?

![image](https://user-images.githubusercontent.com/38434825/173154649-b9011745-c6bc-4dab-9348-117a51080304.png)

**Comment by jasonpetersen** [comment]
Hello. The **/min** folder is a clone of the Minify repository located here: [https://github.com/mrclay/minify](https://github.com/mrclay/minify) Simply follow the instructions on their install guide.

Thanks for your interest!

**Comment by jmcscript** [comment]
A fast and clear response, you are the man of the hour, sir! I'll get it
done and report back to you as soon as possible. Thanks!

**Comment by jmcscript** [comment]
Your readme.md in the min folder says this, and it clearly went over my head. Sorry about the hassle. I might recommend modifying your instructions slightly to something like:

> Clone the [minify](https://github.com/mrclay/minify) repository into this folder (min), which also requires that you install [composer](https://getcomposer.org/download/).

**Comment by jasonpetersen** [comment]
Good notes! I just applied your suggested changes.
